### ISSUE TITLE
Update 105 Experimental 1 breaks BetterHands

### ISSUE THREAD

**Issue by mrwallace888** [Maiq-The-Dude/BetterHands#10]
It's a given that mods are going to break on the Experimental branch, that's why it's an Experimental branch of course. Unfortunately, BetterHands suffers this fate.

**Comment by Maiq-The-Dude** [comment]
I have a fix, but I'm holding off until U105 is released to main branch (or maybe alpha) since the fix will break for anyone not on U105. I'm also looking into expanding magpalming to support the new attachable firearms.

**Comment by Maiq-The-Dude** [comment]
Fixed with release [v1.7.0](https://github.com/Maiq-The-Dude/Better1911/releases/tag/1.5.2). I'll update the Thunderstore listing once U105 has released on main/alpha branch.

Closing this issue, but feel free to reopen if you encounter any U105E1 specific bugs with the new release. Thanks!
