### ISSUE TITLE
Cannot reload

### ISSUE THREAD

**Issue by Dylan-Hatz** [Maiq-The-Dude/BetterHands#11]
Whenever I have this mod enabled, all of the guns that use magazines become impossible to reload because the magazine never clicks into place no matter how close I get them. Non-magazine guns(revolvers, lever action, single shot, etc) work perfectly fine, but any and all guns with mags are busted.

**Comment by Maiq-The-Dude** [comment]
Hi, are you running version 1.7 on the game's `main` branch? 1.7 only supports the "newer" branches `alpha` or `experimental`. 

Downgrade betterhands to 1.6 to keep playing on H3VR's `main` branch
