### ISSUE TITLE
Can't pick up certain shotgun shells and magazines

### ISSUE THREAD

**Issue by TheGreat101** [Maiq-The-Dude/BetterHands#12]
I'm on the main branch of h3vr and have other mods installed
I can't pick up certain shotgun shells and magazines and this error repeats over and over in the console if I try. Using the quick grab seems to teleport the magazine or shell to my hand and it then falls to the ground not staying in my hand even if holding the hold button.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
NGA.MagAnimations/FVRFireArmMagazineFVRFixedUpdate.Postfix (FistVR.FVRFireArmMagazine) <0x00a89>
(wrapper dynamic-method) FistVR.FVRFireArmMagazine.DMD<FistVR.FVRFireArmMagazine..FVRFixedUpdate> (FistVR.FVRFireArmMagazine) <0x00e18>
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<FistVR.FVRFireArmMagazine..FVRFixedUpdate>?-1921950848 (FistVR.FVRFireArmMagazine) <0x0001c>
BetterHands.MagPalming.MagPalmFunctionality.FVRFireArmMagazine_FVRFixedUpdate (On.FistVR.FVRFireArmMagazine/orig_FVRFixedUpdate,FistVR.FVRFireArmMagazine) <0x0002b>
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<FistVR.FVRFireArmMagazine..FVRFixedUpdate>?-1218049536 (FistVR.FVRFireArmMagazine) <0x0005f>
FistVR.FVRInteractiveObject.GlobalFixedUpdate () <0x00123>
FistVR.FVRInteractiveObjectManager.FixedUpdate () <0x0002e>
The problem and error go away if I disable this mod.

**Comment by Maiq-The-Dude** [comment]
I don't have my VR setup currently, but next time you play could you test this without the NGA ReloadAnimations mod installed? 
That mod is patching one of the same methods betterhands patches and is at the top of your stack trace, so I'm guessing there is a conflict. Thanks

**Comment by TheGreat101** [comment]
yep, it turns out there was some problem with the reload animations mod. After a bit more testing I found the error actually still happens with just the reload animations mod enabled, so I think this mod is in the clear.
