### ISSUE TITLE
Can I apply plam on clips but doesn't affect guns?

### ISSUE THREAD

**Issue by Mikumikuer** [Maiq-The-Dude/BetterHands#2]
This mod by default setting can only holding magazines or enblock clips in palm, If i want to enable it for other clips(such as enfield's clip, holding 2 clips will be helpful), I need turn on cursedpalm settings, and it also affect with guns, caused a lot of bugs.
Is there a method to apply it to all clips and magazines but not affect with guns?

**Comment by Maiq-The-Dude** [comment]
Being able to palm clips was added in commit 2f58138ef0dd3a1f3bfa3d3ba0f1d48dd2362e95 which hasn't been released yet. 
If you would like to try it before release, you can download the newest unreleased build from the Actions tab.
