### ISSUE TITLE
Mag palming doesnt support non-physical mags.

### ISSUE THREAD

**Issue by One-Trick-Viper** [Maiq-The-Dude/BetterHands#3]
As the title suggets, currently with non-physical mags enabled, palmed magazines will retain their collisions instead of being able to phase through the gun.

**Comment by Maiq-The-Dude** [comment]
Is this on the latest release? 1.0 did not have this feature whereas 1.1 should I believe.

**Comment by One-Trick-Viper** [comment]
I still appear to be on 1.0, I will install the latest version and check it out.

**Comment by Maiq-The-Dude** [comment]
Cool, let me know. The new version requires Deli 0.3 so be aware of the different installation method.

**Comment by One-Trick-Viper** [comment]
yeah, everything works fine now.
