### ISSUE TITLE
Collision Prevention No working.

### ISSUE THREAD

**Issue by G894** [Maiq-The-Dude/BetterHands#5]
Hi Devs,

First thanks for making this mod. 

I tried to config the cfg file. 

Below is my setting. 

 Prevents physics clanking by disabling palmed item collision while moving above CollisionPreventionVelocity. Only for smooth locomotion
Setting type: Boolean
Default value: true
CollisionPrevention = true

Threshold for CollisionPrevention to kick in for palmed items. Lower to 0 to never have collision on the palmed item
Setting type: Single
Default value: 1.5
CollisionPreventionVelocity = 0

I have tried to reload and restart the game but the palming mag still collide with holding mag & gun when moving. Better Hands version 1.1.1 latest H3vr(no alpha)  Index set and locomotion is twin sticks(it is a smooth locomotion right?)

**Comment by Maiq-The-Dude** [comment]
Thank you for the details.

Yes, twin stick is smooth loco. What specific magazine/gun were you trying this on? I made an optimization change in 1.1.1 to collision prevention, but it is possible some magazines are set up differently than others and thus do not work with the change.

**Comment by G894** [comment]
All kind of the mags I tried are collided, first I thought was the mod change no taking effect, but I can change the position of the palming item and the key mapping.

Anyway here is my mod list, do you think could be any of the other mods causing this issue?

![image](https://user-images.githubusercontent.com/35980805/119442672-dac54600-bd5a-11eb-912e-bb9082edc7ce.png)

**Comment by Maiq-The-Dude** [comment]
No, it doesn't look like anything in there would cause an issue.

Are you testing this by moving in the game or just rotating/spinning in place? Right now it uses positional velocity, so rotating/spinning won't actually activate the collision prevention (something I want to change).

Either way, I haven't been able to replicate this yet but I'm also in the process of rewriting much of BetterHands. I'll try to continue investigating and see if I can find the issue. Thanks!

**Comment by G894** [comment]
I tested it with normal gameplay, moving around and shooting with left hand palming a mag and holding a fore grip at the same time. The palming mag keep knocking things off my gun. 

No problem take your time. If you needed I would happy to provide a video. Just let me know. 

Thanks again.

**Comment by Maiq-The-Dude** [comment]
If you are up for it, would you mind giving this new [updated version](https://github.com/Maiq-The-Dude/BetterHands/suites/2869017875/artifacts/64095717) a try whenever you jump in H3VR next? This is an early build of BetterHands 1.2.0 which is largely rewritten and has a different method for `CollisionPrevention` now.

This new update requires Deli's supplemental H3VR library, [Deli.H3VR](https://github.com/Deli-Collective/Deli.H3VR/releases/tag/v0.2.0), if you don't already have it.

**Comment by Maiq-The-Dude** [comment]
Closed for inactivity and due to new releases. Feel free to reopen this if versions 1.2 or 1.3 still have the issue you described.
