### ISSUE TITLE
Collision issues still persist.

### ISSUE THREAD

**Issue by mrwallace888** [Maiq-The-Dude/BetterHands#9]
The collisions weren't there even when standing still.

-Palmed mags and rounds don't collide with anything, not even the actual game world.
-CollisionPrevention is set to false.
-EasyPalmLoading is set to false.
-The game's vanilla "Easy Mag Loading" is set to false.

The issue still persists. Console log isn't showing anything either, no errors or anything.

Unsure if it depends on the map I start in, I usually notice it at first on Breaching Proto but it occurs with all the other maps too.

Also, palmable speedloaders?

**Comment by Maiq-The-Dude** [comment]
Closing this and reopening the og.
